### ISSUE TITLE
About ground truth data and prediction

### ISSUE THREAD

**Issue by hscspring** [cchamber/Infant_movement_assessment#1]
In file `get_pose_model_predictions_and_groundtruth.py`, there are two paths:

image_path = '/path/to/image/directory'
gt_path = '/path/to/json/file/containing/ground/truth/labels'

though there is an instruction here:

>Compare performance of pose estimation models, e.g. before and after transfer learning.
Compute and visualize error of trained pose estimation model using ground truth data (images and key point labels in COCO format.
Requires ground-truth data (images and joint position labels). Ground-truth labelled data is not provided here.

I still feel a little confused when i'm using.

Would u please send several sample images and annotations?

---- 

another question is prediction. 
If i got a video, I have learned to extract its `features.pkl`, so what should i do next ? 
Should i o merge data sets and compute Gaussian naive Bayesian surprise like the `merge_data_sets.py`?

that's so, thanks to u, and your nice job.

**Comment by aFewThings** [comment]
Same here. Did you solved your problem?
